{
 "title": "New dashboard",
 "description": "SNMP-Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Consumo CPU SNMP Exporter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_clab_node_name=\"snmp-exporter\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consumo CPU Nokia Switch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{container_label_clab_node_name=\"srlswitch2\"}[1m]) * 100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate() In Multicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInMulticastPkts{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInMulticastPkts{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInMulticastPkts{ifName=\"ethernet-1/3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInMulticastPkts{ifName=\"ethernet-1/4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "rate() Out Multicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutMulticastPkts{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutMulticastPkts{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutMulticastPkts{ifName=\"ethernet-1/3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutMulticastPkts{ifName=\"ethernet-1/4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate In Discard Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInDiscards{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifInDiscards{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifInDiscards{ifName=\"ethernet-1/3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifInDiscards{ifName=\"ethernet-1/4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate In Error Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifInErrors{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifInErrors{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifInErrors{ifName=\"ethernet-1/3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifInErrors{ifName=\"ethernet-1/4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "In Unicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"ethernet-1/3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInUcastPkts{ifName=\"ethernet-1/4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Out Unicast Pkts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "pps" } },
   "targets": [
    {
     "expr": "rate(ifOutUcastPkts{ifName=\"ethernet-1/1\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifOutUcastPkts{ifName=\"ethernet-1/2\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifOutUcastPkts{ifName=\"ethernet-1/3\"}[1m])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifOutUcastPkts{ifName=\"ethernet-1/4\"}[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic rate In Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCInOctets{ifName=\"ethernet-1/1\"}[1m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"ethernet-1/2\"}[1m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"ethernet-1/3\"}[1m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCInOctets{ifName=\"ethernet-1/4\"}[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Traffic Rate Out Octets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "rate(ifHCOutOctets{ifName=\"ethernet-1/1\"}[1m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"ethernet-1/2\"}[1m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"ethernet-1/3\"}[1m]) * 8",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(ifHCOutOctets{ifName=\"ethernet-1/4\"}[1m]) * 8",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}